version: 6.4.0.{build}
branches:
  only:
  - master
  - develop
image: Visual Studio 2022
install:
 - ps: Install-Product node 16.13.0
before_build:
 - ps: dotnet restore
build:
  verbosity: normal
after_build:
- pwsh: ./pack.ps1
