version: 6.4.0.{build}
branches:
  only:
  - master
  - develop
image: Visual Studio 2022
install:
 - ps: Install-Product node 16.13.0
before_build:
- ps: dotnet restore
build_script:
- ps: dotnet pack -c Release -o artifacts
test_script:
- ps: dotnet test
artifacts:
- path: artifacts\*.nupkg
